version: '3'

services:
  app:
    build: .
    container_name: demo
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/docker_test
      - SPRING_DATASOURCE_USERNAME=docker_test
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: docker_test
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always