version: '3'

services:
  app:
    build: .
    container_name: demo
    ports:
      - "8080:8080"
    restart: always
  db:
    image: postgres:11.4-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: docker_test
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always