version: '3'

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8080:8080"
      - "8000:8000"
    command: java -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:8000 -jar backend.jar
    #    restart: always
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/docker_test
      - SPRING_DATASOURCE_USERNAME=docker_test
      - SPRING_DATASOURCE_PASSWORD=123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: docker_test
      PGDATA: /var/lib/postgresql/data/pgdata
#    restart: always
  frontend:
    build: ./frontend
    container_name: front
    volumes:
      - './frontend:/app'
      - '/app/node_modules'
    ports:
      - "8081:8081"